layout_spectrum: 0.830827
typography_spectrum: 0.9570454
color:
  saturation: 0.1380236
  brandStrength: 0.5300752
  lightness: 0.7846402
  rhythmicContrast: 0.8093448
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Jon-W
